### ISSUE TITLE
Inconsistency with inbuilt commands

### ISSUE THREAD

**Issue by Technohacker** [YarnSpinnerTool/Docs#10]
Hello!

According to the [Working With Commands page](https://github.com/YarnSpinnerTool/Docs/blob/master/docs/unity/working-with-commands.md#built-in-commands), there are only two built-in commands: `stop` and `wait`. However, in the [Expressions and Variables](https://yarnspinner.dev/docs/writing/expressions-and-variables/#variables) page, there's an additional `set` command.

I have an implementation of Yarn for Godot which implements just `stop` and `wait`. Which of these two define the spec of the Yarn implementation? I wanted to see whether the set command was in the formal spec for this PR https://github.com/Technohacker/godot_yarn_spinner/pull/4#discussion_r537303760

Thanks!

**Comment by desplesda** [comment]
`set` isn't a command, because it has specific syntax that must follow it:a variable name, the assignment operator `=` or `to`, and an expression. It's absolutely part of the spec for the language, because without it, a Yarn script can't modify any values.

(Also: the Godot implementation looks really cool!)

**Comment by Technohacker** [comment]
Ah alright, so I could just consider it as an internal "command" of sorts for my own use since it uses the same notation :D

(Thanks! Made it a Yarn-to-GDScript transpiler so the Engine does all the execution work for me :joy: :grin:)
